# C-/ as prefix
unbind C-b
set-option -g prefix C-_
bind-key C-_ send-prefix

set -s escape-time 0
set -g mouse on
set -g repeat-time 0 # disable repeat (r flag for bind)
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# bind "prefix + r" to reload configuration file
bind r source-file ~/.tmux.conf 

# vim-like pane switching
bind ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

bind v split-window -h
bind s split-window -v

unbind n
bind -r n new-window

unbind q
bind -r q killp # kill pane

unbind t
bind-key t set-option -g status

unbind f
bind f resize-pane -Z

# Color settings
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",alacritty:RGB"
